# Generated by Django 5.1.2 on 2024-10-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('typename', models.CharField(max_length=100)),
                ('inches', models.FloatField(null=True)),
                ('ram', models.IntegerField(null=True)),
                ('os', models.CharField(max_length=50)),
                ('weight', models.FloatField(null=True)),
                ('price_euros', models.FloatField()),
                ('screen', models.CharField(max_length=100)),
                ('screen_width', models.FloatField(null=True)),
                ('screen_height', models.FloatField(null=True)),
                ('touchscreen', models.BooleanField(null=True)),
                ('ips_panel', models.BooleanField(null=True)),
                ('retina_display', models.BooleanField(null=True)),
                ('cpu_company', models.CharField(max_length=100, null=True)),
                ('cpu_freq', models.FloatField(null=True)),
                ('cpu_model', models.CharField(max_length=100)),
                ('primary_storage', models.CharField(max_length=100)),
                ('secondary_storage', models.CharField(max_length=100, null=True)),
                ('primary_storage_type', models.CharField(max_length=50, null=True)),
                ('secondary_storage_type', models.CharField(max_length=50, null=True)),
                ('gpu_company', models.CharField(max_length=100)),
                ('gpu_model', models.CharField(max_length=100)),
            ],
        ),
    ]
